config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'hikes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/hikes/map', to: 'hikes#map'
  get '/hikes/admin', to: 'hikes#admin'
  resources :hikes, only: %i[index show edit update new create destroy] do
    resources :reviews, only: %i[index show new create]
    resources :scores, only: %i[index show new create]
  end
  get '/hikes/:id/destination', to: 'hikes#destination', as: 'destination'


  resources :reviews, only: %i[destroy edit update]

  resources :scores, only: %i[edit update destroy]

  get 'my_scores', to: 'scores#my_scores'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hike.rb
class Hike < ApplicationRecord
  has_many :scores, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
  has_one_attached :gpx

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, :latitude, :longitude, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :hike
  belongs_to :user
  has_many_attached :photos

  validates :content, :rating, :difficulty, presence: true
  validates :content, length: { minimum: 5 }
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :hike
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :scores
  has_one_attached :photo

  validates :firstName, :lastName, :email, :password, presence: true
  validates :email, format: { with: /\A.*@.*\.com\z/ }, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo, :firstName, :lastName ])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end

  def default_url_options
    { host: ENV["www.climbly.live"] || "localhost:3000" }
  end
end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController
  before_action :set_hike, only: %i[show edit update destination destroy]
  helper_method :get_markers, :average

  def index
    @hikes = Hike.where(approved: true)
    if params[:query].present?
      @hikes = @hikes.where('name ILIKE ?', "%#{params[:query]}%")
      # binding.pry
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'shared/card_hike', locals: { hikes: @hikes }, formats: [:html] }
    end
  end

  def show
    @markers = [
      {
        lat: @hike.latitude,
        lng: @hike.longitude,
        image_url: helpers.asset_url("hiker.png")
      }
    ]
  end

  def edit
  end

  def update
    @hike.update(params_hike)
    redirect_to hikes_admin_path
  end

  def new
    @hike = Hike.new
  end

  def create
    @hike = Hike.new(params_hike)
    # @hike.user_id = current_user.id
    if @hike.save
      redirect_to root_path
    else
      render :new
    end
  end

  def map
    @hikes = Hike.all

    @markers = @hikes.geocoded.map do |hike|
      {
        lat: hike.latitude,
        lng: hike.longitude,
        info_window: render_to_string(partial: "info_window", locals: { hike: hike }),
        image_url: helpers.asset_url("hiker.png")
      }
    end
  end

  def destination
    @marker = [{
      lat: @hike.latitude,
      lng: @hike.longitude,
      image_url: helpers.asset_url("hiker.png")
    }]
  end

  def destroy
    @hike.destroy
    redirect_to root_path
  end

  def admin
    @hikes = Hike.where(approved: false)
  end

  private

  def set_hike
    @hike = Hike.find(params[:id])
  end

  def params_hike
    params.require(:hike).permit(:name, :description, :photo, :latitude, :longitude, :address, :gpx, :approved)
  end

  def get_markers(hike)
    hike = Hike.find(hike.id)
    @markers = [
      {
        lat: hike.latitude,
        lng: hike.longitude,
        image_url: helpers.asset_url("hiker.png")
      }
    ]
  end

  def average(hike)
    reviews = hike.reviews
    total = 0
    if reviews != []
      reviews.each do |review|
        total += review.difficulty
      end
      total / reviews.size
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[show edit update]

  def index
    @hike = Hike.find(params[:hike_id])
    @reviews = Review.where(hike_id: params[:hike_id])
  end

  def show
  end

  def edit
  end

  def update
    @review.update(review_params)
    redirect_to hike_reviews_path(@review.hike_id)
  end

  def new
    @hike = Hike.find(params[:hike_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @hike = Hike.find(params[:hike_id])
    @review.user = current_user

    @review.hike = @hike
    if @review.save
      redirect_to hike_reviews_path(params[:hike_id])
    else
      render :new
    end
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :rating, :difficulty, photos: [])
  end
end

app/controllers/scores_controller.rb
require 'open-uri'
require 'json'

class ScoresController < ApplicationController
  before_action :set_score, only: %i[show update]
  helper_method :format_duration

  def index
    @scores = Score.where(hike_id: params[:hike_id]).order("duration ASC").limit(10)
  end

  def show
  end

  def new
    @score = Score.new
    @hike = Hike.find(params[:hike_id])
    @marker = [{
      lat: @hike.latitude,
      lng: @hike.longitude,
      image_url: helpers.asset_url("hiker.png")
    }]
    get_route
  end

  def create
    @hike = Hike.find(params[:hike_id])
    end_date = Time.now
    @score = Score.new(params_score)
    sec = (@score.startDay.to_f / 1000).to_s
    @score.duration = end_date - Time.strptime(sec, '%s')
    @score.user = current_user
    @score.hike = @hike
    @score.save
    redirect_to hike_scores_path(@hike)
  end

  def my_scores
    @all_scores = Score.where(user_id: current_user)
  end

  private

  def set_score
    @score = Score.find(params[:id])
  end

  def params_score
    params.require(:score).permit(:startDay)
  end

  def format_duration(time)
    hours = time / 3600
    minutes = time % 3600 / 60
    seconds = time % 60
    "#{hours}h #{minutes}min #{seconds}sec"
  end

  def get_route
    gpx = Cloudinary::Search
      .expression(@hike.gpx.key)
      .execute
    gpx = gpx.to_h
    url = gpx["resources"][0]["secure_url"]
    file = URI.open(url).read
    doc = Nokogiri::XML(file)
    trackpoints = doc.xpath('//xmlns:trkpt')
    @route = []
    trackpoints.each do |trkpt|
      lat = trkpt.xpath('@lat').to_s.to_f
      lon = trkpt.xpath('@lon').to_s.to_f
      ele = trkpt.text.strip.to_f
      @route << [lon, lat, ele]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/hikes/_info_window.html.erb
<div class="card-hike" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path(hike.photo.key) %>);">
  <div class="container">
    <h2><%= hike.name %></h2>
  </div>
</div>

app/views/hikes/_show.html.erb
<h1>SHOW</h1>

app/views/hikes/admin.html.erb
<div class="banner pages-margin-top" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/deqc25xt2/image/upload/v1654623611/Climbly/forest-mountain-flat-design-vector-banner-template-forest-mountain-flat-design-vector-banner-template-good-web-banner-ads-226266311_buo7wk.jpg);">
  <div class="container">
    <h1>Admin</h1>
    <p>Validate a hike for the public</p>
  </div>
</div>

<div class='container container-list all-cards-container'>
    <%= render "shared/card_hike", hikes: @hikes %>
    <br><br><br><br><br><br>
</div>

app/views/hikes/destination.html.erb
<div class="pages-margin-top map-container" style="width: 100vw; height: 100vh;"
  data-controller="destination"
  data-destination-markers-value="<%= @marker.to_json %>"
  data-destination-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
<div class="d-flex align-items-center btn-container">
  <%= link_to "Ready?", new_hike_score_path(@hike), class: "btn btn-primary btn-container btn-login " %>
</div>

app/views/hikes/edit.html.erb
<div class="container pages-margin-top pages-margin-bottom input-card">
  <div class="card-input-container" data-controller="approval">
    <h2><%= @hike.name %></h2>
    <%= simple_form_for @hike do |f| %>
      <p>testing a new things needed an old project</p>
      <div class="input-field">
        <%= f.input :name, class: 'input-field'%>
      </div>

      <div class="input-field content-field">
        <%= f.input :description, class: 'input-field' %>
      </div>

      <div class="input-field">
        <%= f.input :latitude, class: 'input-field' %>
      </div>

      <div class="input-field">
        <%= f.input :longitude, class: 'input-field' %>
      </div>

      <div class="input-field">
        <%= f.input :address, class: 'input-field' %>
      </div>

      <div class="input-field">
        <%= f.input :photo, as: :file, class: 'input-field'%>
      </div>

      <div class='d-none'>
        <%= f.input :approved, input_html: { data: { approval_target: "input"} }%>
      </div>

      <div class="d-flex justify-content-center input-field">
        <%= f.submit 'Approve & Save Changes', class: "btn btn-success", data: { confirm: "Do you wish to post this new hike ?",
                                                                                 action: "click->approval#validate"
                                                                               } %>
      </div>

      <div class="d-flex justify-content-center input-field" style="margin-top: 4px;">
        <%= link_to 'Delete', hike_path(@hike), method: :delete, data: {confirm: "Do you wish to delete this new hike request?"}, class: "btn btn-danger", style: "width: 220px;" %>
      </div>
    <% end %>
  </div>
</div>

app/views/hikes/index.html.erb
<div class="banner pages-margin-top" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/deqc25xt2/image/upload/v1654623611/Climbly/forest-mountain-flat-design-vector-banner-template-forest-mountain-flat-design-vector-banner-template-good-web-banner-ads-226266311_buo7wk.jpg);">
  <div class="container">
    <h1>Climbly</h1>
    <p>Discover Mauritius and Challenge yourself with your friends through Hiking.</p>
  </div>
</div>

<div class='container container-list'>
    <%= render "shared/card_hike", hikes: @hikes %>
    <br><br><br><br><br><br>
</div>

app/views/hikes/map.html.erb
<div class="pages-margin-top map-container" style="width: 100%; height: 600px;"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/hikes/new.html.erb
<div class="container pages-margin-top pages-margin-bottom card-input-container">
  <h2 class="p-2">Suggested Hike</h2>
  <div class="card-new-hike">
    <h2> How would you describe your suggested hike? </h2>
    <%= simple_form_for [@hike] do |f| %>
      <div class="container input-field">
        <%= f.input :name, placeholder: 'Add a name' %>
        <%= f.input :description, placeholder: 'Add a description' %>
        <%= f.input :latitude, placeholder: 'Add a latitude' %>
        <%= f.input :longitude, placeholder: 'Add a longitude' %>
        <%= f.input :photo, as: :file %>
        <%= f.input :gpx, as: :file %>
      </div>
      <div class="d-flex justify-content-between">
        <%= f.submit 'Post', class: "btn btn-default btn-success btn-post" %>
        <%= link_to 'Skip', hikes_path, class:"btn btn-default btn-primary btn-skip"%>
      </div>
    <% end %>
  </div>
</div>

app/views/hikes/show.html.erb
<div class="card-hike-show" >
  <div class="banner d-flex justify-content-center">
  <h1><%=@hike.name %></h1>
  </div>

  <div class="container">
    <div class="row">

      <div class="review-btn col-8">
      <%= link_to "Review", hike_review_path(@hike), class: "btn btn-primary" %>
      </div>

      <div class="scores-btn col-4">
      <%= link_to "Scores", hike_scores_path(@hike), class: "btn btn-primary" %>
      </div>

    </div>
  </div>

  <%# <div class="back-btn d-flex justify-content-flex-start">
  <%= link_to "Back", root_path, class: "btn btn-primary" %>
  <%# </div> %>


  <%# <div class="scores-btn">
  <%= link_to "Scores", hike_scores_path(@hike), class: "btn btn-primary" %>
  <%# </div>  %>

  <div class="container mt-3">
    <div class="row justify-content-center">
      <div class="col-10">
        <div class="h3-text-container">
          <h3 class="pb-2">A propos </h3>
        </div>
        <div class="description-body">
          <i class="fas fa-quote-left"></i><p> <%= @hike.description %> </p> <i class="fas fa-quote-right d-flex justify-content-end"></i>
        </div>
        <div class="difficulty-body">
          <%# <p> <%= @review.difficulty %>
        </div>
      </div>
    </div>

  <div class="container">
      <div class="row">

        <div class="back-btn col-8">
        <%= link_to "Back", root_path, class: "btn btn-primary" %>
        </div>

        <div class="select-btn col-4">
        <%= link_to "Select", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>

  <div style="width: 300px; height: 300px;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>

  <%# <div class="d-flex align-items-center">
  <%= link_to "Select", class: "btn btn-primary" %>
  <%# </div> %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">


    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
  </head>


  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/edit.html.erb
<div class="container pages-margin-top pages-margin-bottom input-card">
  <div class="card-input-container">
    <h2><%= @review.hike.name %></h2>
    <%= simple_form_for [@hike, @review] do |f| %>

      <div class="input-field">
        <%= f.input :rating, class: 'input-field'%>
      </div>

      <div class="input-field">
        <%= f.input :difficulty, class: 'input-field' %>
      </div>

      <div class="input-field content-field">
        <%= f.input :content, class: 'input-field' %>
      </div>

      <div class="input-field">
        <%= f.input :photos, as: :file, class: 'input-field'%>
      </div>

      <div class="d-flex justify-content-center input-field">
        <%= f.submit 'Save Changes', class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/index.html.erb
<div class="banner pages-margin-top" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/deqc25xt2/image/upload/v1654623611/Climbly/forest-mountain-flat-design-vector-banner-template-forest-mountain-flat-design-vector-banner-template-good-web-banner-ads-226266311_buo7wk.jpg);">
  <div class="container">
    <h1>Reviews</h1>
    <p>All Reviews of <%= @hike.name %> mountain.</p>
  </div>
</div>

<div class="container pages-padding-bottom all-cards-container">
  <%# show text and add review btn %>
  <div class="review-list-text d-flex justify-content-between align-items-center">
    <h1><%= @hike.name %></h1>
    <%= link_to 'Add Review', new_hike_review_path, class:"btn btn-primary btn-post"%>
  </div>

  <%# creates each card %>
  <% if @reviews.empty? %>
    <div class="d-flex justify-content-center align-items-end no-reviews-container">
      <h1>No reviews Yet</h1>
    </div>
  <% else %>
    <% @reviews.each do |review| %>
      <div class="card container d-flex">
        <%# add edit btn to each card %>
        <%# <% raise %>
        <% if current_user.admin? || review.user == current_user %>
          <%= link_to edit_review_path(review) do %>
            <i class="edit-btn fa-solid fa-pen-to-square"></i>
          <% end %>
        <% end %>
        <%# body of each card %>
        <div class="">
          <div class="d-flex justify-content-around">
            <%# adding image to each card %>
            <div>
              <% if review.user.photo.attached? %>
                <%= cl_image_tag review.user.photo.key, class: "avatar avatar-nav" %>
              <% else %>
                <div class="navbar-toggler-profile-basic">
                  <i class="far fa-user-circle"></i>
                </div>
              <% end %>
            </div>
            <%# adding stard to the review and difficulty %>
            <div class="d-flex flex-column container-rat-diff">
              <div class="card-rating-difficulty d-flex align-items-center justify-content-end">
                <h5 class="basic-reset">Rating: </h5>
                <% review.rating.times do %>
                  <i class="fa-solid fa-star"></i>
                <% end %>
              </div>
              <div class="card-rating-difficulty d-flex align-items-center justify-content-end">
                <div>
                  <h5 class="basic-reset">Difficulty: </h5>
                </div>
                <% review.difficulty.times do %>
                  <i class=" fa-solid fa-star"></i>
                <% end %>
              </div>
            </div>
          </div>
          <%# adding review content %>
          <div style="margin-bottom: 8px;">
            <p class="card-text">
              <%= review.content%>
            </p>
          </div>
          <div class="d-flex justify-content-end">
            <%= link_to 'Show content', hike_review_path(@hike, review), class:"btn btn-primary btn-post"%>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="container pages-margin-top pages-margin-bottom card-input-container">
  <h2 class="p-2">Leave a Review</h2>
  <div class="card-review">
  <h2>How would you rate this hike?</h2>
  <%= simple_form_for [@hike, @review] do |f| %>
    <div class="container input-field ">
      <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
      <%= f.input :difficulty, collection: (1..5).to_a, label: "Rate your experience" %>
      <div class="input-field content-field">
        <%= f.input :content, placeholder: 'Write a review' %>
      </div>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    </div>
    <div class="d-flex justify-content-between">
      <%= f.submit 'Post', class: "btn btn-default btn-success btn-post" %>
      <%= link_to 'Skip', hike_reviews_path, class:"btn btn-default btn-primary btn-skip"%>
    </div>
  <% end %>
  </div>
</div>

app/views/scores/index.html.erb
<div class="banner-leaderboard banner pages-margin-top" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/deqc25xt2/image/upload/v1654623611/Climbly/forest-mountain-flat-design-vector-banner-template-forest-mountain-flat-design-vector-banner-template-good-web-banner-ads-226266311_buo7wk.jpg);">
  <div class="container d-flex flex-column">
    <div class="container-text">
      <h1>Leaderboard</h1>
    </div>
    <div class="container-places-leaderboard">
      <% if @scores.empty? == false %>
        <div>
          <% if @scores[0].user.photo.attached? %>
            <%= cl_image_tag @scores[0].user.photo.key, class:'image-1st' %>
          <% else %>
            <%= image_tag("https://res.cloudinary.com/deqc25xt2/image/upload/v1653735226/development/wfpxgqqv8uyjgmxkrcwhvyejjacx.jpg", class:'image-1st') %>
          <% end %>
          <%= image_tag("https://res.cloudinary.com/deqc25xt2/image/upload/v1654864908/Climbly/1st-place-gold-medal-vector-23821321_fihbyq.jpg", class:'first') %>
        </div>
        <div>
          <% if @scores.count > 1 && @scores[1].user.photo.attached?%>
            <%= cl_image_tag @scores[1].user.photo.key, class:'image-2nd' %>
          <% else %>
            <%= image_tag("https://res.cloudinary.com/deqc25xt2/image/upload/v1653735226/development/wfpxgqqv8uyjgmxkrcwhvyejjacx.jpg", class:'image-2nd') %>
          <% end %>
          <%= image_tag("https://res.cloudinary.com/deqc25xt2/image/upload/v1654864884/Climbly/champion-silver-medal-with-red-ribbon-vector-30899176_zumh04.webp", class:'second') %>
        </div>
        <div>
          <% if @scores.count > 2 && @scores[2].user.photo.attached? %>
            <%= cl_image_tag @scores[2].user.photo.key, class:'image-3rd' %>
          <% else %>
            <%= image_tag("https://res.cloudinary.com/deqc25xt2/image/upload/v1653735226/development/wfpxgqqv8uyjgmxkrcwhvyejjacx.jpg", class:'image-3rd') %>
          <% end %>
            <%= image_tag("https://res.cloudinary.com/deqc25xt2/image/upload/v1654864879/Climbly/3rd-place-bronze-medal-vector-23821323_gir3bk.jpg", class:'third') %>
        </div>
      <% else %>
        <div class="d-flex justify-content-center align-items-center" style="color: white;">
          <h2>No scores yet be the first!!</h2>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="container container-list pages-padding-bottom all-cards-container">
  <div class="d-flex justify-content-center">
    <%= link_to "Leave a review", new_hike_review_path, class:"btn btn-primary btn-login" %>
  </div>
  <% @scores.each_with_index do |score, index| %>
    <div class="score-container d-flex justify-content-around ">
      <div class="">
        <% if score.user.photo.attached? %>
          <%= cl_image_tag score.user.photo.key, class: "avatar avatar-nav" %>
        <% else %>
          <div class="navbar-toggler-profile-basic">
            <i class="far fa-user-circle"></i>
          </div>
        <% end %>
      </div>
      <div class="d-flex flex-column text-score-container">
        <p>Name: <%= score.user.firstName %> <%= score.user.lastName %></p>
        <p>Duration: <%= format_duration(score.duration) %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_card_show_details.html.erb
<div class="card-category container container-background-whiter position " >

  <div class="container-card-show-content">

    <div class="banner d-flex justify-content-center banner-container"  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path hike.photo.key || "" %>'); border-radius: 8px; height: 150px;">
      <%= link_to hike_scores_path(hike) do %>
         <i class="fa-solid fa-trophy trophy-icon"></i>
      <% end %>
    </div>
    <div class="d-flex justify-content-between align-items-center padding-top-container">
      <h3>Description:</h3>
      <%= link_to "Reviews", hike_reviews_path(hike), class: "btn btn-light" %>
    </div>

      <i class="fas fa-quote-left"></i><p> <%= hike.description %> </p> <i class="fas fa-quote-right d-flex justify-content-end"></i>
    <h3 >Difficulty:
    <% if average %>
      <% average.times do %>
        <i class=" fa-solid fa-star"></i>
      <% end %>
    <% end %>
    </h3>
    <div style="width: 100%; height: 350px;"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

    <% if hike.approved %>
      <div class="d-flex align-items-center">
        <%= link_to "Select", destination_path(hike), class: "btn btn-primary btn-select", data: { turbolinks: false} %>
      </div>
    <% else %>
      <div class="d-flex align-items-center">
       <%= link_to "Approved ?", edit_hike_path(hike), class: "btn btn-warning btn-select", data: { turbolinks: false} %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer sticky-bottom">
  <div class="footer-container">
    <div class="div-footer-icon">
      <%= link_to root_path do  %>
       <i class="fas fa-home"></i>
      <% end %>
    </div>
    <div class="div-footer-icon">
      <%= link_to hikes_map_path do  %>
       <i class="fa-solid fa-map-location-dot"></i>
      <% end %>
    </div>
    <div class="div-footer-icon">
      <%= link_to my_scores_path do  %>
       <i class="fa-solid fa-ranking-star"></i>
      <% end %>
    </div>

    <div class="div-footer-icon">
      <%= link_to new_hike_path do %>
        <i class="fa-solid fa-circle-plus"></i>
      <% end %>
    </div>
  </div>
</div>